safe:        false
auto:        true
server:      false
server_port: 4000
baseurl:     /jekyll-portfolio
url:         http://localhost:4000
source:      .
destination: ./_site
plugins:     ./_plugins
future:      true
markdown:    maruku
permalink: 	 /portfolio/:title


sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed